### ISSUE TITLE
[FATAL] Premature end of data in tag HTML line 1

### ISSUE THREAD

**Issue by w0rd-driven** [rethink-group/authorize-sdk-php#1]
This is a rough issue to write up as the summary is the exception being returned from `CreateCustomerProfileTransactionController()->executeWithApiResponse()`

The more complete exception is something like this:
```
2019-02-11 16:13:12] production.ERROR: [FATAL] Premature end of data in tag HTML line 1
 in  (line: 10, column: 1) {"exception":"[object] (JMS\\Serializer\\Exception\\XmlErrorException(code: 0): [FATAL] Premature end of data in tag HTML line 1
 in  (line: 10, column: 1) at /home/forge/site/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:69)
[stacktrace]
#0 /home/forge/site/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(111): JMS\\Serializer\\XmlDeserializationVisitor->prepare('<HTML><HEAD>\
<T...')
#1 [internal function]: JMS\\Serializer\\Serializer->JMS\\Serializer\\{closure}(Object(JMS\\Serializer\\XmlDeserializationVisitor))
#2 /home/forge/site/vendor/phpoption/phpoption/src/PhpOption/Some.php(89): call_user_func(Object(Closure), Object(JMS\\Serializer\\XmlDeserializationVisitor))
#3 /home/forge/site/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(115): PhpOption\\Some->map(Object(Closure))
#4 /home/forge/sitevendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php(129): JMS\\Serializer\\Serializer->deserialize('<HTML><HEAD>\
<T...', 'net\\\\authorize\\\\a...', 'xml')
#5 /home/forge/site/vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php(104): net\\authorize\\api\\controller\\base\\ApiOperationBase->execute('https://api2.au...')
```

This exception points to where the problem lies but the response from the call to https://api2.authorize.net/xml/v1/request.api randomly returns

```
<HTML><HEAD>\n
<TITLE>Access Denied</TITLE>\n
</HEAD><BODY>\n
<H1>Access Denied</H1>\n
 \n
You don't have permission to access "http&#58;&#47;&#47;api2&#46;authorize&#46;net&#47;xml&#47;v1&#47;request&#46;api" on this server.<P>\n
Reference&#32;&#35;18&#46;4d83d717&#46;1549903888&#46;727e5a\n
</BODY>\n
</HTML>\n
```

Encoding the access and reference lines results in: `You don’t have permission to access “http://api2.authorize.net/xml/v1/request.api” on this server.<P>\n
Reference #18.4d83d717.1549903888.727e5a\n`

This http vs https may indicate where the problem lies but support explained that this can randomly become an issue. For our environment, this was constant.

**Comment by w0rd-driven** [comment]
The correction we made on the production environment by editing the file directly was to change `https://api2.authorize.net` to `https://api.authorize.net`.

I believe the break to api2 was to facilitate SSL/TLS updates that is likely long migrated over to api.authorize.net, though I personally don't know enough backstory to verify this completely.

Our version is v1.9.7 because we depend on a few breaking changes introduced in 1.9.8+ so the PR will be to make the change to that tag to move v1.9.7.1 forward. Jumping to v2 at the moment seems premature due to some issues with floats and likely other serialization quirks.
